# numpy.array基础

In [2]:
import numpy as np

**为什么要使用numpy?**

## Python　List的特点
1. list数据类型不做限定
2. 效率低

In [15]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
L[5]="Machine"
L0

[0, 1, 2, 3, 4, 'Machine', 6, 7, 8, 9]

In [19]:
import array

In [27]:
arr = array.array('i',[i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Python自身的Array效率比较高,但是不支持矩阵与向量,限定太多

In [22]:
arr[5] = 'Machine'

TypeError: an integer is required (got type str)

## numpy.array的实例
numpy的优势:
1. 效率高
2. 不用指明数据类型
3. 支持矩阵运算

In [28]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
nparr.dtype

dtype('int64')

In [32]:
nparr[5] = 5.2
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
nparr2 = np.array([1,2,3.0])
nparr2.dtype

dtype('float64')

## 其他创建 numpy.array的方法

In [35]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
np.zeros(shape = (3,5),dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [43]:
np.ones(shape = (3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

注意使用full的时候机器会自己判断设置的是什么类型,如果设置666.0那么就是浮点数

In [3]:
np.full(shape=(3,5) , fill_value = 666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

## 关于arange
1. Python自带的range不能传入浮点数
2. arange比range要好写
3. 三个参数意义是[0,20)区间步长为2生成一个数组

In [45]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
[i for i in range(0,20,2.0)]

TypeError: 'float' object cannot be interpreted as an integer

In [48]:
np.arange(0,20,2.5)

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5])

## 类似于arange的linspace
**linspace的区间是[x,y]的**
特点是第三个参数意义是等长的截取多少段

In [51]:
np.linspace(0,20,15)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        , 11.42857143, 12.85714286,
       14.28571429, 15.71428571, 17.14285714, 18.57142857, 20.        ])

## numpy的random
区间也是前闭后开的

In [52]:
np.random.randint(0,10)

9

In [55]:
np.random.randint(0,1,size = 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [56]:
np.random.randint(0,5,size = (3,5))

array([[3, 1, 3, 4, 2],
       [0, 0, 2, 1, 1],
       [4, 1, 4, 0, 2]])

In [57]:
#指定随机种子
#显然种子一样生成的随机数就一样
np.random.seed(666)

In [58]:
np.random.randint(0,5,size = (3,5))

array([[4, 2, 1, 4, 3],
       [3, 4, 4, 1, 0],
       [0, 2, 4, 4, 3]])

In [59]:
np.random.seed(666)
np.random.randint(0,5,size = (3,5))

array([[4, 2, 1, 4, 3],
       [3, 4, 4, 1, 0],
       [0, 2, 4, 4, 3]])

In [60]:
np.random.random(size = 10)

array([0.00510884, 0.11285765, 0.11095367, 0.24766823, 0.0232363 ,
       0.72732115, 0.34003494, 0.19750316, 0.90917959, 0.97834699])

In [61]:
##生成一个符合正态分布的随机矩阵
np.random.normal(0,1,(3,5))

array([[-1.68290077,  0.22918525, -1.75662522,  0.84463262,  0.27721986],
       [ 0.85290153,  0.1945996 ,  1.31063772,  1.5438436 , -0.52904802],
       [-0.6564723 , -0.2015057 , -0.70061583,  0.68713795, -0.02607576]])