In [1]:
import numpy as np

In [5]:
X = np.arange(15).reshape(3,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
x.shape

(10,)

In [9]:
X.shape

(3, 5)

In [10]:
X.size

15

In [11]:
x.ndim

1

In [12]:
X.ndim

2

## numpy.array的数据访问

In [13]:
x[-1]

9

In [16]:
X[0,0]

0

In [17]:
X[2,2]

12

In [18]:
X[-1,0]

10

In [19]:
x[:5]

array([0, 1, 2, 3, 4])

In [20]:
x[2:5]

array([2, 3, 4])

In [21]:
x[::2]

array([0, 2, 4, 6, 8])

In [22]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [24]:
#注意如果用两个方括号则这里会出现问题
X[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [25]:
X[:2,::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [26]:
X[::-1,::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [29]:
subX = X[:2,:3]
subX

array([[100,   1,   2],
       [  5,   6,   7]])

## numpy中为了效率,在修改切片的时候会改变原来的矩阵

In [28]:
subX[0,0]=100
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [30]:
subX = X[:2,:3].copy()
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [31]:
subX[0,0]=0
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

## Reshape命令

In [32]:
x.reshape(2,4)
x

ValueError: cannot reshape array of size 10 into shape (2,4)

In [34]:
x.reshape(2,5)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 合并操作

In [35]:
x=np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [36]:
z = np.array([666,666,666])
np.concatenate([x,y,z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [38]:
A = np.array([[1,2,3],
             [4,5,6]])
np.concatenate([A,A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [40]:
np.concatenate([A,A],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [42]:
#第一种方法
np.concatenate([A,z.reshape(1,-1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [43]:
np.vstack([A,z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [44]:
B = np.full((2,2),100)

In [45]:
np.hstack([A,B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

## 数据的分割操作

In [48]:
x=np.arange(10)
x1,x2,x3=np.split(x,[3,7])
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
x1,x2,x3

(array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9]))

In [49]:
A=np.arange(16).reshape((4,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [50]:
A1,A2 = np.split(A,[2])
A1,A2

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]))

In [53]:
A1,A2 = np.split(A,[2],axis=1)
A1,A2

(array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]))

In [54]:
np.vsplit(A,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [57]:
left,right=np.hsplit(A,[2])
left,right

(array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]))