# numpy.array中的运算
给定一个向量,让向量的每一个数字乘以2

a = (1 ,2,3)
a*2=(2,4,6)



## python自身的array能否做向量计算?

In [1]:
L=[i for i in range(10)]
2*L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
n=1000000
L = [i for i in range(n)]

In [3]:
%%time
A = [2*e for e in L]

CPU times: user 36 ms, sys: 20 ms, total: 56 ms
Wall time: 65.3 ms


In [4]:
import numpy as np

In [5]:
L = np.arange(n)

In [6]:
%%time
A = np.array(2*e for e in L)

CPU times: user 12 ms, sys: 0 ns, total: 12 ms
Wall time: 10.6 ms


In [7]:
%%time
A = 2*L

CPU times: user 4 ms, sys: 0 ns, total: 4 ms
Wall time: 4.94 ms


In [8]:
n=10
L = np.arange(n)
2*L

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Universal Functions

In [9]:
X = np.arange(1,16).reshape(3,5)
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [10]:
X+1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [11]:
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [12]:
np.tan(X)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00],
       [-2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01,  6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01]])

In [13]:
np.power(3,X)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]])

In [14]:
np.log2(X)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809],
       [3.45943162, 3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

## 矩阵运算

In [15]:
A=np.arange(4).reshape(2,2)

In [16]:
B=np.full((2,2),10)

In [17]:
A+B

array([[10, 11],
       [12, 13]])

In [18]:
A*B

array([[ 0, 10],
       [20, 30]])

In [19]:
A.dot(B)

array([[10, 10],
       [50, 50]])

In [20]:
A.T

array([[0, 2],
       [1, 3]])

## 向量和矩阵的运算

In [21]:
v = np.array([1,2])
v+A

array([[1, 3],
       [3, 5]])

In [22]:
A

array([[0, 1],
       [2, 3]])

In [23]:
np.vstack([v] * A.shape[0])

array([[1, 2],
       [1, 2]])

In [24]:
np.tile(v,(2,1))

array([[1, 2],
       [1, 2]])

In [25]:
v * A

array([[0, 2],
       [2, 6]])

In [26]:
v.dot(A)

array([4, 7])

In [36]:
A.dot(v)

array([2, 8])

In [28]:
A.dot(v)

array([2, 8])

In [42]:
  # a:  矩阵与行向量 相乘(mxn * 1*n 形式)， 此时行向量长度 必须等于矩阵的列数

  #  b：矩阵与列向量相乘(mxn  * mx1 形式) 此时 矩阵的行数必须与列向量的行数相同
    a = np.array([
        [1, 2],
        [4,5],
        [7,8]
    ])
    b = np.array([2,3])
    a.dot(b) #即 行向量 每个元素乘以 矩阵的对应列
    c = np.array([2,3,4])
    print(c.dot(a))  ##不可以 3X2 * 1x3

[42 51]


## 矩阵的逆

In [29]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [30]:
invA = np.linalg.inv(A)
invA.dot(A)

array([[1., 0.],
       [0., 1.]])

In [31]:
X = np.arange(16).reshape(2,8)

In [32]:
pinvX = np.linalg.pinv(X)
pinvX

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -7.30583920e-18],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [33]:
X.dot(pinvX)

array([[ 1.00000000e+00, -2.77555756e-16],
       [ 1.69309011e-15,  1.00000000e+00]])