In [2]:
import numpy as np

In [3]:
L = np.random.random(100)
L

array([0.26476026, 0.48637066, 0.90830131, 0.57962952, 0.27051432,
       0.74944976, 0.32825911, 0.83149307, 0.67899215, 0.40051403,
       0.96363931, 0.79244589, 0.5644897 , 0.33077513, 0.57070029,
       0.69853818, 0.15302684, 0.69497821, 0.52956179, 0.62354127,
       0.23344886, 0.37113426, 0.85657073, 0.69893835, 0.36622319,
       0.28214201, 0.26468896, 0.53156673, 0.67271404, 0.59033086,
       0.35908075, 0.39209273, 0.7055062 , 0.00605241, 0.32175953,
       0.80795232, 0.11553165, 0.88174319, 0.83748642, 0.07981477,
       0.88071063, 0.68250007, 0.68481403, 0.20290086, 0.12964923,
       0.64168591, 0.66179778, 0.04396269, 0.24979174, 0.0835281 ,
       0.60761427, 0.56428219, 0.76606525, 0.4087774 , 0.61855484,
       0.85737002, 0.27845476, 0.64942572, 0.28775398, 0.55646062,
       0.95766223, 0.60822612, 0.65334178, 0.08180611, 0.46427846,
       0.64082343, 0.45773315, 0.6938464 , 0.35699553, 0.75236844,
       0.76596555, 0.91395343, 0.14552896, 0.11555446, 0.80272

In [4]:
sum(L)

50.45473363068681

In [5]:
np.sum(L)

50.45473363068679

In [6]:
big_array = np.random.random(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

98.3 ms ± 1.59 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
560 µs ± 10.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [7]:
np.max(big_array)

0.9999986137678352

In [8]:
np.min(big_array)

2.697779316607196e-07

In [9]:
big_array.sum()

499608.27487791376

In [10]:
X = np.arange(16).reshape(4,-1)

In [11]:
np.sum(X)

120

In [14]:
#按列计算
np.sum(X,axis=0)

array([24, 28, 32, 36])

In [15]:
#按行计算
np.sum(X,axis=1)

array([ 6, 22, 38, 54])

In [16]:
np.prod(X)

0

In [17]:
#累乘
np.prod(X+1)

20922789888000

In [18]:
#平均值
np.mean(X)

7.5

In [19]:
#中位数
np.median(X)

7.5

In [21]:
#百分位点
np.percentile(big_array,q=50)

0.4994893036364305

In [22]:
#求方差
np.var(X)

21.25

In [23]:
#标准差
np.std(X)

4.6097722286464435

In [25]:
x = np.random.normal(0,1,size=100000)

In [26]:
np.var(x)

0.9951845094879355

In [27]:
np.mean(x)

-0.0028374474075322825

## 索引

In [28]:
np.argmin(x)

18361

In [29]:
x[18361]

-4.41871851826973

In [30]:
np.min(x)

-4.41871851826973

In [31]:
np.argmax(x)

72383

## 排序和使用索引

In [32]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [34]:
np.random.shuffle(x)
x

array([11, 14, 12,  3,  8,  5,  0,  7,  9, 13,  2,  1, 10,  6, 15,  4])

In [35]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [36]:
x

array([11, 14, 12,  3,  8,  5,  0,  7,  9, 13,  2,  1, 10,  6, 15,  4])

In [38]:
x.sort()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [39]:
x = np.random.randint(10,size=(4,4))

In [40]:
np.sort(x)

array([[2, 3, 6, 9],
       [1, 4, 4, 5],
       [1, 5, 7, 7],
       [5, 5, 7, 7]])

In [41]:
x

array([[3, 2, 6, 9],
       [4, 4, 5, 1],
       [7, 1, 5, 7],
       [7, 5, 7, 5]])

In [42]:
np.sort(x,axis=1)

array([[2, 3, 6, 9],
       [1, 4, 4, 5],
       [1, 5, 7, 7],
       [5, 5, 7, 7]])

In [43]:
np.sort(x,axis=0)

array([[3, 1, 5, 1],
       [4, 2, 5, 5],
       [7, 4, 6, 7],
       [7, 5, 7, 9]])

In [44]:
np.argsort(x)

array([[1, 0, 2, 3],
       [3, 0, 1, 2],
       [1, 2, 0, 3],
       [1, 3, 0, 2]])

In [45]:
x

array([[3, 2, 6, 9],
       [4, 4, 5, 1],
       [7, 1, 5, 7],
       [7, 5, 7, 5]])

In [47]:
x = np.arange(16)
np.random.shuffle(x)
np.partition(x,3)

array([ 0,  2,  1,  3,  5,  4,  6, 14, 15, 12,  8, 13,  7, 11,  9, 10])

In [48]:
x

array([10,  2,  3,  9, 11,  8, 14,  5, 15, 12,  4, 13,  7,  1,  0,  6])

In [49]:
np.argpartition(x,3)

array([14,  1, 13,  2,  7, 10, 15,  6,  8,  9,  5, 11, 12,  4,  3,  0])